### ISSUE TITLE
Unity2019.4.40f1编译报错，'SocketNetworkChannel'未定义

### ISSUE THREAD

**Issue by gameboys84** [AlianBlank/GameFrameX.Unity#1]
按文档要求，更新了GameFrameX，并将Unity工程checkout到GameFrameX子目录下。

使用Unity打开工程后，这个代码报错
> Library\PackageCache\com.alianblank.gameframex.unity.network@b5b7d5a2ec\Runtime\Network\Network\NetworkManager.cs(195,53): error CS0246: The type or namespace name 'SocketNetworkChannel' could not be found (are you missing a using directive or an assembly reference?)

经查，本地确实没有这个类的实现SocketNetworkChannel。
报错的代码如下：
```
#if ENABLE_GAME_FRAME_X_WEB_SOCKET && UNITY_WEBGL
            NetworkChannelBase networkChannel = new WebSocketNetworkChannel(channelName, networkChannelHelper);
#else
            NetworkChannelBase networkChannel = new SocketNetworkChannel(channelName, networkChannelHelper);
#endif
```

运行环境：
Unity2019.4.40f1
PC platform
没有开启WebGL

**Comment by AlianBlank** [comment]
由于网络的部分还在修改中。这个部分还没弄好。服务器在支持多进程的模式

**Comment by AlianBlank** [comment]
已修复该问题
