### ISSUE TITLE
ShowEntity 之后 在 GetEntity 就会报空引用

### ISSUE THREAD

**Issue by cc10vv2007** [AlianBlank/GameFrameX.Unity#2]
GameApp.Entity.ShowEntity<Logic>(entityID, entityAssetName, entityGroupName,  userData);
Entity entity = GameApp.Entity.GetEntity(entityID);

运行环境：
Unity2022.3
PC platform
没有开启WebGL

**Comment by cc10vv2007** [comment]
运行环境：
Unity2019.4.40f1
PC platform
没有开启WebGL

**Comment by AlianBlank** [comment]
已修复
